# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'google.com.br'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy DEV
        
  deploy-hmg:
    runs-on: ubuntu-latest
    environment:
      name: hmg
      url: 'google.com.br'
    needs: deploy-dev
    steps:
      - name: Run a one-line script
        run: echo Deploy HMG
        
  deploy-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
      url: 'google.com.br'
    needs: deploy-hmg
    steps:
      - name: Run a one-line script
        run: echo Deploy PRD
        
      
